# SITE CONFIGURATION
url: "https://sylhare.github.io"
title: Ciudades abiertas
description: "Website del portal del proyecto Ciudades abiertas"


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Ciudades abiertas # blog's title
  avatar: assets/img/logo.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Icons
  rss: false
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: ciudadesabiertas
exclude: ["Gemfile", "Gemfile.lock", "ciudades-abiertas.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]